### ISSUE TITLE
Undefined reference with Qt

### ISSUE THREAD

**Issue by florian02100** [googleapis/google-cloud-cpp#3323]
Hello everyone,

i've problem with google-cloud-cpp i've install it and i try to use it on QtCreator but i've error : 

 **undefined reference to `google::cloud::v0::StatusCodeToString[abi:cxx11]`(google::cloud::v0::StatusCode)'**

I've included all lib (*.a and *.so) and i've set my environment path.

I don't understand. Have you any ideas ? 

Thanks

**Comment by coryan** [comment]
Can you tell us something about what platform was this on?  Linux presumably?  What distro? What compiler?

Did you use the same options (specially `-std=c++11`) to compiler your code and the libraries?

When you say "all lib", does that include `libgoogle_cloud_cpp_common.{a,so}`?

**Comment by Ninconji** [comment]
I try to be same things and we solved this error with terminal and using make.
Know we have an error " undefined reference to 

> google::cloud::storage::v1::Client::CreateDefaultClient()

_"
I work with Qt too, on ubuntu (18.04).
I  compile with c++11, i have inclued all lib (libgoogle_cloud_cpp_common too).

**Comment by coryan** [comment]
Thank you for the additional details.  Unfortunately I still cannot figure out why you would get this error, would it be possible for you to attach instructions and/or a small program to reproduce the issue?

**Comment by devjgm** [comment]
From: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

> If you get linker errors about undefined references to symbols that involve types in the std::__cxx11 namespace or the tag [abi:cxx11] then **it probably indicates that you are trying to link together object files that were compiled with different values for the _GLIBCXX_USE_CXX11_ABI macro**. This commonly happens when linking to a third-party library that was compiled with an older version of GCC.

**Comment by Ninconji** [comment]
I follow this tutorials:
->https://cloud.google.com/storage/docs/reference/libraries?hl=fr
->https://github.com/googleapis/google-cloud-cpp

For now i just try  to connect my project c++ with google cloud storage.
I writed this code.
```
#include "google/cloud/storage/client.h"
 namespace gcs = google::cloud::storage;
    google::cloud::StatusOr<gcs::Client> client =
        gcs::Client::CreateDefaultClient();
    if (!client) {
      std::cerr << "Failed to create Storage Client, status=" << client.status()
                << "\n";
    }
```
I try to this with a button.

**Comment by coryan** [comment]
Based on the last comment it seems like this question was answered.
